language: python
python:
  - "3.2"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
before_script:
  - cd python3
script: tests/runall.py
